server:
  port: ${SERVER_PORT:9090}
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:huyokno01}
    hikari:
      poolName: Hikari
      auto-commit: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: postgresql
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    generate-ddl: ${JPA_GENERATE_DDL:true}
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
